### ISSUE TITLE
MATCH with property=NULL crashes redis

### ISSUE THREAD

**Issue by aminazar** [RedisLabsModules/RedisGraph#115]
`CREATE (:label{a:10,b:'abc'})`

`CREATE (:label{a:20,b:'cba',c:'c'})`

`MATCH (r:label) WHERE r.c=NULL RETURN r`

Above crashes redis-graph server (running on docker on Mac).

**Comment by swilly22** [comment]
Hi @aminazar,
Just to be clear, you're trying to find nodes which do not have the 'c' attribute?

**Comment by swilly22** [comment]
GRAPH.QUERY G "MATCH (r:label) WHERE exists(r.c) = false RETURN r"
