### ISSUE TITLE
Can't create a vertex that has more than 23 properties

### ISSUE THREAD

**Issue by tperry** [RedisLabsModules/RedisGraph#195]
I'm not able to create a vertex that contains more than 23 properties. The first query below works but the second one fails.

GRAPH.QUERY testDB 'CREATE (:v0{p1:1,p2:2,p3:3,p4:4,p5:5,p6:6,p7:7,p8:8,p9:9,p10:10,p11:11,p12:12",p13:13,p14:14,p15:15,p16:16,p17:17,p18:18,p19:19,p20:20,p21:21,p22:22,p23:23})'
1) (empty list or set)
2) 1) Labels added: 1
   2) Nodes created: 1
   3) Properties set: 23
   4) "Query internal execution time: 0.110965 milliseconds"

GRAPH.QUERY testDB 'CREATE (:v0{p1:1,p2:2,p3:3,p4:4,p5:5,p6:6,p7:7,p8:8,p9:9,p10:10,p11:11,p12:12",p13:13,p14:14,p15:15,p16:16,p17:17,p18:18,p19:19,p20:20,p21:21,p22:22,p23:23,p24:24})'
(error) Syntax error at offset 164 near '}'

**Comment by swilly22** [comment]
@tperry I've quickly looked into it and I must said i'm puzzled, I'll have to dig a little bit deeper,
Thanks for reporting!

**Comment by swilly22** [comment]
Fixed #207
