### ISSUE TITLE
Q: on Redis keys

### ISSUE THREAD

**Issue by davisford** [RedisLabsModules/RedisGraph#196]
This is just a general curiosity question....I note that redisgraph creates several keys to store nodes, edges, etc....

```
$redis-cli keys "*" | xargs redis-cli del
(integer) 16
$ redis-cli
127.0.0.1:6379> GRAPH.QUERY rgt "CREATE (o:org {id:1, type:'org'})"
1) (empty list or set)
2) 1) Labels added: 1
   2) Nodes created: 1
   3) Properties set: 2
   4) "Query internal execution time: 1.523018 milliseconds"
127.0.0.1:6379> keys *
1) "redis_graph_store_rgt_NODE_org"
2) "rgt"
3) "redis_graph_store_rgt_NODE_ALL"
```

Just curious what `storetype` is and can it be introspected at all with any standard Redis commands (so far I've had no luck)

```
127.0.0.1:6379> type "redis_graph_store_rgt_NODE_org"
storetype
```

**Comment by swilly22** [comment]
RedisGraph introduces a number of custom datatypes, `storetype` is one of them, in some details a storetype is basically a prefix-tree which keeps track of attributes introduced to some node/edge type.
and so when a query asks to retrieve a node of type T we know which attributes to expect.

Unfortunately you can't inspect custom datatypes using standard Redis commands.

**Comment by jeffreylovitz** [comment]
Note that we just refactored this a few hours ago, and each graph is now stored under a single key!

```
127.0.0.1:6379>  GRAPH.QUERY rgt "CREATE (o:org {id:1, type:'org'})"
1) (empty list or set)
2) 1) "Labels added: 1"
   2) "Nodes created: 1"
   3) "Properties set: 2"
   4) "Query internal execution time: 0.613614 milliseconds"
127.0.0.1:6379> KEYS *
1) "rgt"
127.0.0.1:6379> type rgt
graphdata
```

**Comment by davisford** [comment]
Oh kewl... @jeffreylovitz !

**Comment by jeffreylovitz** [comment]
@davisford Would you try running `make clean`, then `make`?

**Comment by davisford** [comment]
All set now -- gotta wipe out the old db, but that's not a problem for me.

`68627:M 31 Oct 2018 16:16:03.628 # The RDB file contains module data I can't load: no matching module 'storetype'`

**Comment by swilly22** [comment]
Yeah, that's backward compatibility we've just broken, as the first official version has yet to come out (Nov 15) we allow ourselves to make breaking changes.

Once the official version will be release we will do anything in our power to be backwards compatible.

**Comment by K-Jo** [comment]
@davisford Can we close this issue?
