### ISSUE TITLE
Feature Request: support wildcard to pull whole graph

### ISSUE THREAD

**Issue by davisford** [RedisLabsModules/RedisGraph#197]
It would be useful to be able to pull back the entire graph.  A lot of times, I am creating semi-complex graphs, and would be useful to cross-check what's in the database vs. what I *think* is in the database.  Currently the only way to do that is to execute various queries, but if those queries are wrong...or not matching what I think is in there, it doesn't work.

In SQL land, what I'm asking for is something like `SELECT * FROM table`.  Perhaps in redisgraph parlance something like `GRAPH.QUERY testdb "MATCH ()"` (returns all nodes) and `GRAPH.QUERY testdb "MATCH ()-[]->()"` returns the *entire* graph.

Not sure how difficult this is, but it would be very useful

**Comment by swilly22** [comment]
You can defiantly issue both queries:

`GRAPH.QUERY testdb "MATCH (n) RETURN n"` to get all nodes in the graph
and 
`GRAPH.QUERY testdb "MATCH ()-[e]->() RETURN e"` returns all edges

I can see how this is not exactly returning the entire graph,
I think we need to better define the structure of a response which returns an entire graph

**Comment by davisford** [comment]
Yea, the alias is what's preventing it from doing this, eh?  `MATCH (n)-[e]->() RETURN n, e` -- b/c I think that query will only return specific adjacencies even tho the label is unspecified?

A wildcard character like `*` would be useful here....?

**Comment by swilly22** [comment]
Correct, the query will return all nodes / relations, regardless of their labels.

A wildcard can be used, which will simply return all entities specified within the MATCH clause.
So I think `MATCH ()-[]->() RETURN *` should return the first node, edge and the second node, you don't need to specify aliases.

But as you probably already noticed we've yet to support '*'
