### ISSUE TITLE
Question: Support 'flash' in ramp file ?

### ISSUE THREAD

**Issue by ofirnk** [RedisLabsModules/RedisGraph#204]
Hi,
Is there a reason not to specify `flash` as supported capability in https://github.com/RedisLabsModules/RedisGraph/blob/master/ramp.yml ?

Thanks

**Comment by itamarhaber** [comment]
Hello Ofir,

The 'flash' capability is used by Redis Labs Enterprise Cluster to determine compatibility with the company's Flash-based engine. It should be used in an Enterprise Cluster to indicate compatibility.

**Comment by ofirnk** [comment]
@itamarhaber I know, but when it is not specified in the `ramp` file it will be disabled in Redis enterprise for the specific deployment .. AFAIK

**Comment by itamarhaber** [comment]
I would assume that is because RedisGraph is yet to be officially supported on Redis on Flash. Are you a Redis on Flash user, and are you looking to use RedisGraph with it?

**Comment by ofirnk** [comment]
Exactly - I think the value for RedisGraph on Flash could be enormous.

Btw, from my understanding it's the other way around - a module should report that it supports flash.
Does it require something more than simply changing the [Capabilities section](https://github.com/RedisLabsModules/RedisGraph/blob/master/ramp.yml#L10) ?

**Comment by itamarhaber** [comment]
Changing the capabilities section is the easy part - actually making sure it works is a different matter :)

**Comment by ofirnk** [comment]
Is there a specific test suite for flash?

**Comment by itamarhaber** [comment]
Yes, but Flash support isn't only a matter of passing the tests. Depending on the module, the data structures that it uses and the way it allocates memory, it may or may not benefit from using Flash.

That said, this discussion appears to be digressing. RedisGraph on Flash is on the team's roadmap, and we'd be happy to learn about any requirements you may have.
