### ISSUE TITLE
Graph serialization error in duplicate edge handling

### ISSUE THREAD

**Issue by jeffreylovitz** [RedisLabsModules/RedisGraph#218]
We only currently permit one edge for each [source, destination, relation type] triplet, but don't have logic to enforce that at the time of edge creation yet.

Perhaps our efforts would be best spent solving that, but I'm writing up a downstream effect of this so that it doesn't get confused for an independent error.

```
15:27 $ redis-cli GRAPH.QUERY G "CREATE (a:l)-[:ee]->(b:l), (a)-[:ee]->(b)"                                                                                   
1) (empty list or set)                                                                                                                                        
2) 1) "Labels added: 1"                                                                                                                                       
   2) "Nodes created: 2"                                                                                                                                      
   3) "Relationships created: 2"                                                                                                                              
   4) "Query internal execution time: 0.670682 milliseconds"                                                                                                  
✔ ~/dev/redis/graph [master|…64⚑ 57]
15:27 $ redis-cli shutdown
[relaunch server]
12613:M 06 Nov 15:28:10.822 # Server initialized
12613:M 06 Nov 15:28:10.823 * <graph> Thread pool created, using 8 threads.
12613:M 06 Nov 15:28:10.823 * Module 'graph' loaded from /home/tower-linux/dev/redis/graph/src/redisgraph.so
12613:M 06 Nov 15:28:10.823 # Error loading data from RDB (short read or EOF). Read performed by module 'graph' about type 'graphdata' after reading '0' bytes of a value.
```

What's happening here is that we create the same edge twice, adding both to the datablocks but not modifying the `nnz` count of the edge matrices. When we save the matrices, we save the datablock-reported number as the edge count, but use a tuples iter to save the edges themselves, which stops once it's depleted all matrix entries.

When we try to load, subsequently, we run out of RDB elements before reaching the expected edge count.

**Comment by esokullu** [comment]
I just had the same:
`Error loading data from RDB (short read or EOF). Read performed by module 'graph' about type 'graphdata' after reading '0' bytes of a value.`

**Comment by esokullu** [comment]
I cannot restart the server. Please help.

**Comment by jeffreylovitz** [comment]
Sorry about that! Since this error occurs while Redis is trying to read keys, it has no way to recover gracefully.

If you don't have any important data in the rdb file you're currently using, you can just delete it (by default, this is 'dump.rdb' in the directory you're invoking from). This will delete the entire database.

If you can't afford to lose the rdb file, it will have to be modified by hand. Let me know if this is necessary, and I will try to help.

**Comment by esokullu** [comment]
Yes 🙏 will be backing up more frequently. How can I send it to you privately?

**Comment by esokullu** [comment]
Amassed 5MB of data in a few days since launch and there was no backup :(

**Comment by jeffreylovitz** [comment]
My apologies, again! Please contact me at jeffrey.lovitz@gmail.com - if you're able to send the rdb file itself, that would be ideal, otherwise I can try to guide you through.

**Comment by esokullu** [comment]
I appreciate. Sent you an email. Should we perhaps enable AOF in the interim for increased durability with RedisGraph? Would it help?

**Comment by jeffreylovitz** [comment]
RedisGraph keys can only be serialized through RDB at present, so I'm afraid that would be unlikely to help! We'll try to get this bug resolved as soon as possible.

**Comment by esokullu** [comment]
@jeffreylovitz one more bug here. Even though the master server is running now (with your fixed dump.rdb)  and it's all clean, when I try to add a slave to it, the slave server fails.

```
root@redis-1-slave-1:~# redis-server /etc/redis/redis.conf 
2708:C 18 Dec 2018 01:29:01.691 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2708:C 18 Dec 2018 01:29:01.691 # Redis version=5.0.2, bits=64, commit=00000000, modified=0, pid=2708, just started
2708:C 18 Dec 2018 01:29:01.691 # Configuration loaded
2708:C 18 Dec 2018 01:29:01.691 # systemd supervision requested, but NOTIFY_SOCKET not found
2708:S 18 Dec 2018 01:29:01.692 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 5.0.2 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 2708
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

2708:S 18 Dec 2018 01:29:01.693 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
2708:S 18 Dec 2018 01:29:01.693 # Server initialized
2708:S 18 Dec 2018 01:29:01.693 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
2708:S 18 Dec 2018 01:29:01.693 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
2708:S 18 Dec 2018 01:29:01.696 * <graph> Thread pool created, using 3 threads.
2708:S 18 Dec 2018 01:29:01.696 * Module 'graph' loaded from /opt/RedisGraph/src/redisgraph.so
2708:S 18 Dec 2018 01:29:01.712 # Error loading data from RDB (short read or EOF). Read performed by module 'graph' about type 'graphdata' after reading '0' bytes of a value.
````

Not urgent like the previous one. But FYI.

**Comment by esokullu** [comment]
@jeffreylovitz sent you an important email. Please take a look. Thank you.

**Comment by jeffreylovitz** [comment]
The root bug here is that RedisGraph does not allow for multiple relations of the same type between the same two nodes. This assumption is not checked on edge creation, however, which can cause the number of relations a graph believes it contains to not reflect the number of relations it holds data for.

When the graph is saved to an RDB file, first the count is saved, then all relation data is saved - an operation that is dependent on the actual relation data rather than the count.
When the graph is loaded, we first read the count, then try to load relation data that many times. Since in this scenario, the count is greater than the actual number of relations, this stage will read further than it ought to.
The confusion that results will, ultimately, cause the graph key to fail to load. This is an irrecoverable error, as Redis will not know how to continue deserializing keys.

Until the root error is fixed, I've added a branch to this repo named `restore-broken-rdb`: https://github.com/RedisLabsModules/RedisGraph/tree/restore-broken-rdb

Launching a server using this branch will cause the loading routines to look for some improbable markers in edge deserialization - specifically, loading an edge with the ID 0 after one or more edges with IDs greater than 0.

This is an unlikely scenario, but not an invalid one, making this an unsafe assumption as an actual fix. This is additionally not an actual fix because once all relations have been loaded, indices are loaded - if the module did just read too far, that 0 was meant to indicate the number of indices attached to the graph. This fix will thus not work if the graph contains any indices.

We are considering ways to resolve the root issue without suffering significant performance degradation when building relationships. Until then, hopefully this patch will help ameliorate the issue!
