### ISSUE TITLE
Support directionless relationship queries

### ISSUE THREAD

**Issue by serdaroquai** [RedisLabsModules/RedisGraph#238]
Any plans to add support for directionless queries?

`MATCH (A)-[FRIEND]-(B) RETURN A, B`

**Comment by jeffreylovitz** [comment]
We definitely intend to add support for this! The most naive implementation would be pretty trivial to implement (basically, repeat certain operations with source and destination ID swapped), though it's an important enough feature that we should consider our options.

I don't know when this addition will fit into our release timetable, so for the moment I'm going to promote it as issue #239.

**Comment by swilly22** [comment]
Yeah, defiantly on our roadmap, we'll be prioritising our tasks throughout next week,
I'll update here when I have a better understanding on when we'll be able to accommodate this

**Comment by K-Jo** [comment]
Duplicate: https://github.com/RedisLabsModules/RedisGraph/issues/239
