### ISSUE TITLE
Bulk  insert crashes Redis

### ISSUE THREAD

**Issue by zanek** [RedisLabsModules/RedisGraph#246]
I ran the bulk loader like so:  "python bulk_insert.py TEST -n nodes.txt -r r1.txt "

I used 48 relationship files as well . 

Below is all the info that was printed out from the server

6481:M 19 Nov 17:53:06.748 * DB saved on disk
redis-server: /home/zanek/RedisGraph/src/graph/graph.c:372: Graph_ConnectNodes: Assertion `Graph_GetNode(g, dest, &destNode)' failed.
Aborted (core dumped)

**Comment by swilly22** [comment]
It might be that your relationships file r1.txt refers to a none existing node ID,
The way bulk-insert currently works is by creating every node within your nodes.txt file, IDs are assigned to newly created nodes by the order they're listed, so the first node will be assigned ID 0, assuming you've got N nodes in total, then the last node will be assigned ID N-1.

Within your relationships file r1.txt you may refer only to IDs 0..N-1.

**Comment by zanek** [comment]
I actually write all my nodes to a dictionary with a unique number
(starting at zero and increasing for each new node) and then write out all
the relationships using the assigned numbers.

This prevents me from using an non-existent relationship number

Redis shouldn’t crash either way. It should not be that brittle

I’ll double check my input files in the morning

Thanks

**Comment by jeffreylovitz** [comment]
@zanek, agreed about the crash - we're considering options for friendlier exception handling, and will improve that area soon.

The Python bulk insert script does now validate that the node IDs referenced by relationship files are always less than N, and your method sounds perfectly appropriate, so I wouldn't expect any issues there.

What does the output of the script look like? How far has the insertion proceeded before crashing, and how many total entities are you inserting?

**Comment by zanek** [comment]
Here is the output from the bulk loader script

Building label descriptors...
Initialized a graph to accommodate 1524817 nodes and 3119141 edges.
Inserting Label "nodes" - 1524817 nodes
22.92% (349521 / 1524817) of "nodes" inserted.
45.84% (699042 / 1524817) of "nodes" inserted.
68.77% (1048563 / 1524817) of "nodes" inserted.
91.69% (1398084 / 1524817) of "nodes" inserted.
Finished inserting "nodes".
1524817 nodes created in 5 queries.
Inserting relation "r1" - 18628 edges
Inserting relation "r2" - 27746 edges
Inserting relation "r3" - 22677 edges
Inserting relation "r4" - 16801 edges
Inserting relation "r5" - 4688 edges
Inserting relation "r6" - 263 edges
Inserting relation "r7" - 441 edges 
Inserting relation "rx2" - 2173 edges
Inserting relation "rx2" - 177453 edges
Inserting relation "es3" - 3170 edges
Inserting relation "tr2" - 3396 edges
Inserting relation "wx" - 405 edges
Inserting relation "df3" - 4183 edges
Inserting relation "kg3" - 41304 edges
Inserting relation "lp2" - 353780 edges
Traceback (most recent call last):
  File "bulk_insert.py", line 284, in <module>
    bulk_insert()
  File "/home/zanek/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zanek/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zanek/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zanek/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bulk_insert.py", line 280, in bulk_insert
    relation_descriptors.batch_insert_descriptors()
  File "bulk_insert.py", line 71, in batch_insert_descriptors
    query_redis(self, entities)
  File "bulk_insert.py", line 210, in query_redis
    result = redis_client.execute_command(*cmd)
  File "/home/zanek/.local/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/zanek/.local/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/zanek/.local/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/zanek/.local/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

**Comment by swilly22** [comment]
@zanek Please make sure to use bulk-insert script from
Also please make sure both lp2 and the relationship csv files which follows don't refer to IDs greater than 1524816, lower than 0.

**Comment by zanek** [comment]
Thanks,  I found the issue.  My bulk import has no issues now
