### ISSUE TITLE
Server crashes on trying to join on indexed field

### ISSUE THREAD

**Issue by dipeti** [RedisLabsModules/RedisGraph#257]
After inserting each node individually I would like to build their relationships by joining them on a property which happens to be indexed. 
```
GRAPH.QUERY DEMO_GRAPH "CREATE (:book {id: 'B1', title: 'Johns First Book', authorId: 'P1'})"
GRAPH.QUERY DEMO_GRAPH "CREATE (:book {id: 'B2', title: 'Johns Second Book', authorId: 'P1'})"
GRAPH.QUERY DEMO_GRAPH "CREATE (:author {id: 'P1', name: 'John'})"
GRAPH.QUERY DEMO_GRAPH "CREATE INDEX ON :author(id)"
GRAPH.QUERY DEMO_GRAPH "MATCH (a:author), (b:book) WHERE a.id='P1' AND b.authorId=a.id CREATE (a)-[:wrote]->(b)"
```
Executing this block of commands results in redis-server crashing with an error:
`/src/execution_plan/record.c:33: Record_GetEntry: Assertion `e' failed.`

**Comment by jeffreylovitz** [comment]
Nice catch, @dipeti ! We should be able to fix this shortly.
