### ISSUE TITLE
Adding a deleted relationship, then deleting the node will cause redis to crash

### ISSUE THREAD

**Issue by mrzhanginchina** [RedisLabsModules/RedisGraph#261]
Add a relationship: GRAPH.QUERY DEMO_GRAPH "CREATE (jim:person{name:'Jim', age:29})-[:friends]->(pam:person {name:'Pam', age:27})-[:works]->(:employer {name:'Dunder Mifflin'})"
delete three nodes: GRAPH.QUERY DEMO_GRAPH "MATCH (p) where p.name='Jim' or p.name='Pam' or p.name='Dunder Mifflin' DELETE p"
Add the deleted relationship: GRAPH.QUERY DEMO_GRAPH "CREATE (jim:person{name:'Jim', age:29})-[:friends]->(pam:person {name:'Pam', age:27})-[:works]->(:employer {name:'Dunder Mifflin'})"
delete one node in the relationship, then the redis will crash:  GRAPH.QUERY DEMO_GRAPH "MATCH (p:person {name:'Jim'}) delete p"

**Comment by swilly22** [comment]
@mrzhanginchina thank you for reporting a fix been merged to the master branch,
can you please verify?
