### ISSUE TITLE
Using ORDER BY a property which not exists in RETURN crashes Redis Server

### ISSUE THREAD

**Issue by kienhg96** [RedisLabsModules/RedisGraph#267]
127.0.0.1:6379> graph.query test "CREATE (:Person {id: 1, name: 'abc'})"
1) (empty list or set)
2) 1) "Nodes created: 1"
   2) "Properties set: 2"
   3) "Query internal execution time: 0.837572 milliseconds"

127.0.0.1:6379> graph.query test "MATCH (p:Person) RETURN p.name ORDER BY p.id"
Error: Connection reset by peer
(0.63s)

**Comment by swilly22** [comment]
Thank you @kienhg96 for posting,
We're fully aware of this one, hope to get it fix soon

**Comment by swilly22** [comment]
Fixed by #275
