### ISSUE TITLE
Question on MATCH query (<- or ->)

### ISSUE THREAD

**Issue by zhzhbin** [RedisLabsModules/RedisGraph#269]
Hi,

I'm testing some MATCH queries, and found some question.
Am I doing something wrong, my understanding is wrong, or is this a bug?

something like:

I have a simple graph: 2 persons. Persons A knows B.

```
CREATE (:person{name:'name A', last_name:'last A'})
CREATE (:person{name:'name B', last_name:'last B'})

MATCH (a:person), (b:person) WHERE (a.name = 'name A' AND b.name='name B') CREATE (a)-[:knows]->(b)
```

These 2 queries have a result that does not look correct:

When I use this :

`MATCH (a:person)-[b]->(c:person) RETURN a,TYPE(b) as d,c`

result data is success , 

but when I use like this:

`MATCH (a:person)<-[b]-(c:person) RETURN a,TYPE(b) as d,c`

there's no data result

**Comment by swilly22** [comment]
Hey @zhzhbin thanks for letting us know,
a fix was just merged, can you please verify?

**Comment by zhzhbin** [comment]
Sorry,I use docker now.I couldn't compile source

**Comment by swilly22** [comment]
@zhzhbin latest tag should be uptodate.

**Comment by zhzhbin** [comment]
I used the docker image tag edge,it updated at two days ago. but the question as before 
![image](https://user-images.githubusercontent.com/19484539/49293642-aa82f080-f4eb-11e8-9b04-cc938a29757e.png)
![image](https://user-images.githubusercontent.com/19484539/49293532-609a0a80-f4eb-11e8-978a-1d6f4f22e6ef.png)

**Comment by jeffreylovitz** [comment]
Sorry, the updated Docker image is still building! I'll ping here once it's finished.

**Comment by zhzhbin** [comment]
> Sorry, the updated Docker image is still building! I'll ping here once it's finished.

thank you

**Comment by zhzhbin** [comment]
This was fast! Thanks!
Got the right results
Thanks Everyone
