### ISSUE TITLE
Query Result does not recognize when the connection has decode_responses=True

### ISSUE THREAD

**Issue by schwab** [RedisLabsModules/RedisGraph#282]
If the underlying redis connection object has been initialized with decode_responses=True, then redis graph throws an exception in the QueryResult_get_value @staticmethod when decoding stat details.  
The workaround at this point is to always use decode_responses=False  (the default) for the underlying redis connection for redisgraph queries; however, this complicates applications which use redis both key_value and redis graph purposes as now at least 2 connections to the redis server must be maintained.

**Comment by swilly22** [comment]
Hi @schwab,
would you mind moving this issue over to [redisgraph-py](https://github.com/RedisLabs/redisgraph-py)
Thank you

**Comment by schwab** [comment]
OK, done.
