### ISSUE TITLE
Server crashes on updating node property

### ISSUE THREAD

**Issue by jkxplg** [RedisLabsModules/RedisGraph#302]
I have a small graph with a node 'a' looking like this:
1) 1) 1) "a.id"
      2) "a.user"
      3) "a.type"
      4) "a.time"
      5) "a.data"
      6) "a.a"
   2) 1) "1002"
      2) "NULL"
      3) "time"
      4) "1002"
      5) "NULL"
      6) "a"

and running  GRAPH.QUERY small_with_dup "MATCH (a:Node{id:'1002'})  SET a.a = a.a + 'a'" crashed the server.

Bug report:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 27 Dec 2018 09:14:36.573 # Redis 5.0.1 crashed by signal: 11
1:M 27 Dec 2018 09:14:36.573 # Crashed running the instruction at: 0x7fcd37be67d0
1:M 27 Dec 2018 09:14:36.573 # Accessing address: (nil)
1:M 27 Dec 2018 09:14:36.573 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(+0x947d0)[0x7fcd37be67d0]

Backtrace:
redis-server *:6379(logStackTrace+0x37)[0x55b44203aa27]
redis-server *:6379(sigsegvHandler+0xb0)[0x55b44203b150]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110c0)[0x7fcd37f020c0]
/lib/x86_64-linux-gnu/libc.so.6(+0x947d0)[0x7fcd37be67d0]
/usr/lib/redis/modules/redisgraph.so(SIValue_ToString+0xf3)[0x7fcd353ccf23]
/usr/lib/redis/modules/redisgraph.so(+0xa1bf2)[0x7fcd353e4bf2]
/usr/lib/redis/modules/redisgraph.so(ResultSet_AddRecord+0x85)[0x7fcd353e5c85]
/usr/lib/redis/modules/redisgraph.so(ProduceResultsConsume+0x5e)[0x7fcd353d5c0e]
/usr/lib/redis/modules/redisgraph.so(ExecutionPlan_Execute+0x29)[0x7fcd353d5829]
/usr/lib/redis/modules/redisgraph.so(_MGraph_Query+0x245)[0x7fcd353ea1e5]
/usr/lib/redis/modules/redisgraph.so(+0xa5224)[0x7fcd353e8224]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x7fcd37ef8494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fcd37c3aacf]

------ INFO OUTPUT ------
# Server

redis_version:5.0.1

redis_git_sha1:00000000

redis_git_dirty:0

redis_build_id:29efca43cc88267

redis_mode:standalone

os:Linux 4.9.125-linuxkit x86_64

arch_bits:64

multiplexing_api:epoll

atomicvar_api:atomic-builtin

gcc_version:6.3.0

process_id:1

run_id:0503619535abc56f25b183d93d01d291dd14c5d0

tcp_port:6379

uptime_in_seconds:104

uptime_in_days:0

hz:10

configured_hz:10

lru_clock:2398204

executable:/data/redis-server

config_file:/etc/redis/redis.conf

# Clients

connected_clients:1

client_recent_max_input_buffer:2

client_recent_max_output_buffer:0

blocked_clients:1

# Memory

used_memory:1850152

used_memory_human:1.76M

used_memory_rss:6701056

used_memory_rss_human:6.39M

used_memory_peak:1985416

used_memory_peak_human:1.89M

used_memory_peak_perc:93.19%

used_memory_overhead:840790

used_memory_startup:791032

used_memory_dataset:1009362

used_memory_dataset_perc:95.30%

allocator_allocated:2836184

allocator_active:3518464

allocator_resident:10911744

total_system_memory:8341340160

total_system_memory_human:7.77G

used_memory_lua:37888

used_memory_lua_human:37.00K

used_memory_scripts:0

used_memory_scripts_human:0B

number_of_cached_scripts:0

maxmemory:4294967296

maxmemory_human:4.00G

maxmemory_policy:allkeys-lru

allocator_frag_ratio:1.24

allocator_frag_bytes:682280

allocator_rss_ratio:3.10

allocator_rss_bytes:7393280

rss_overhead_ratio:0.61

rss_overhead_bytes:18446744073705340928

mem_fragmentation_ratio:3.84

mem_fragmentation_bytes:4955416

mem_not_counted_for_evict:0

mem_replication_backlog:0

mem_clients_slaves:0

mem_clients_normal:49686

mem_aof_buffer:0

mem_allocator:jemalloc-5.1.0

active_defrag_running:0

lazyfree_pending_objects:0

# Persistence

loading:0

rdb_changes_since_last_save:45

rdb_bgsave_in_progress:0

rdb_last_save_time:1545901972

rdb_last_bgsave_status:ok

rdb_last_bgsave_time_sec:-1

rdb_current_bgsave_time_sec:-1

rdb_last_cow_size:0

aof_enabled:0

aof_rewrite_in_progress:0

aof_rewrite_scheduled:0

aof_last_rewrite_time_sec:-1

aof_current_rewrite_time_sec:-1

aof_last_bgrewrite_status:ok

aof_last_write_status:ok

aof_last_cow_size:0

# Stats

total_connections_received:3

total_commands_processed:53

instantaneous_ops_per_sec:0

total_net_input_bytes:11477

total_net_output_bytes:19067

instantaneous_input_kbps:0.00

instantaneous_output_kbps:0.00

rejected_connections:0

sync_full:0

sync_partial_ok:0

sync_partial_err:0

expired_keys:0

expired_stale_perc:0.00

expired_time_cap_reached_count:0

evicted_keys:0

keyspace_hits:47

keyspace_misses:1

pubsub_channels:0

pubsub_patterns:0

latest_fork_usec:0

migrate_cached_sockets:0

slave_expires_tracked_keys:0

active_defrag_hits:0

active_defrag_misses:0

active_defrag_key_hits:0

active_defrag_key_misses:0

# Replication

role:master

connected_slaves:0

master_replid:4b20cf65ab2999c0d6029420be92963551bf7aa1

master_replid2:0000000000000000000000000000000000000000

master_repl_offset:0

second_repl_offset:-1

repl_backlog_active:0

repl_backlog_size:1048576

repl_backlog_first_byte_offset:0

repl_backlog_histlen:0

# CPU

used_cpu_sys:0.130000

used_cpu_user:0.130000

used_cpu_sys_children:0.000000

used_cpu_user_children:0.000000

# Commandstats

cmdstat_graph.DELETE:calls=1,usec=39,usec_per_call=39.00

cmdstat_keys:calls=3,usec=20,usec_per_call=6.67

cmdstat_command:calls=1,usec=591,usec_per_call=591.00

cmdstat_graph.QUERY:calls=48,usec=3330,usec_per_call=69.38

# Cluster

cluster_enabled:0

# Keyspace

db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=3 addr=172.17.0.1:56032 fd=8 name= age=89 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY

------ REGISTERS ------
1:M 27 Dec 2018 09:14:36.583 # 
RAX:00007fcd35112c60 RBX:00007fcd35112c60
RCX:0000000000000000 RDX:0000000000000800
RDI:00007fcd35112c60 RSI:0000ab6886decbb0
RBP:00007fcd35112c60 RSP:00007fcd35112c38
R8 :0000000000000800 R9 :0000000000000004
R10:0000000000000001 R11:00007fcd37caef00
R12:00007fcd1c0056b0 R13:00007fcd359fca78
R14:0000000000000006 R15:00007fcd1c005280
RIP:00007fcd37be67d0 EFL:0000000000010246
CSGSFS:002b000000000033
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c47) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c46) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c45) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c44) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c43) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c42) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c41) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c40) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c3f) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c3e) -> 0000000000000000
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c3d) -> 000000004c4c554e
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c3c) -> 00007fcd353e4bf2
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c3b) -> 0000000000000060
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c3a) -> 000055b4420653bc
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c39) -> 00007fcd1c0056b0
1:M 27 Dec 2018 09:14:36.583 # (00007fcd35112c38) -> 00007fcd353ccf23

------ FAST MEMORY TEST ------
1:M 27 Dec 2018 09:14:36.583 # Bio thread for job type #0 terminated
1:M 27 Dec 2018 09:14:36.584 # Bio thread for job type #1 terminated
1:M 27 Dec 2018 09:14:36.584 # Bio thread for job type #2 terminated
*** Preparing to test memory region 55b44236f000 (2248704 bytes)
*** Preparing to test memory region 55b4436dd000 (258048 bytes)
*** Preparing to test memory region 7fcd1c000000 (135168 bytes)
*** Preparing to test memory region 7fcd24000000 (135168 bytes)
*** Preparing to test memory region 7fcd28000000 (135168 bytes)
*** Preparing to test memory region 7fcd2c000000 (139264 bytes)
*** Preparing to test memory region 7fcd31a00000 (16777216 bytes)
*** Preparing to test memory region 7fcd32b92000 (5767168 bytes)
*** Preparing to test memory region 7fcd33113000 (8388608 bytes)
*** Preparing to test memory region 7fcd33914000 (8388608 bytes)
*** Preparing to test memory region 7fcd34115000 (8388608 bytes)
*** Preparing to test memory region 7fcd34916000 (8388608 bytes)
*** Preparing to test memory region 7fcd359fe000 (8388608 bytes)
*** Preparing to test memory region 7fcd361ff000 (8388608 bytes)
*** Preparing to test memory region 7fcd36a00000 (8388608 bytes)
*** Preparing to test memory region 7fcd37200000 (8388608 bytes)
*** Preparing to test memory region 7fcd37eed000 (16384 bytes)
*** Preparing to test memory region 7fcd3810a000 (16384 bytes)
*** Preparing to test memory region 7fcd38a36000 (24576 bytes)
*** Preparing to test memory region 7fcd38a3e000 (12288 bytes)
*** Preparing to test memory region 7fcd38a43000 (4096 bytes)

Let me know if you need any more info.

**Comment by jeffreylovitz** [comment]
HI @jkxplg,

This crash was caused by an issue in string concatenation, which ought to be resolved now. Can you verify that this is fixed?

**Comment by jkxplg** [comment]
@jeffreylovitz thanks for the reply. This looks to have been fixed.
