### ISSUE TITLE
Multiple relationships of the same relationship type between two nodes

### ISSUE THREAD

**Issue by esokullu** [RedisLabsModules/RedisGraph#316]
I know that with the new serialization method, there can only be one edge of the same type between two particular nodes (hat tip @jeffreylovitz) and new ones would overwrite existing ones.

Is there any plans to change this behavior? If so, any timeline when?

Thanks,

**Comment by swilly22** [comment]
@esokullu Yes, there's a plan on allowing multiple edges of the same type between two particular nodes,
with regard to timeline I'm not sure, our roadmap is quite packed as it is, but I'll do my best to accommodate that addition by the end of February.

**Comment by jkxplg** [comment]
Hi @swilly22, 
Any updates on this?
I know that this is planned for the future, do you, by any chance, have an estimate on a timeline?

Thanks

**Comment by swilly22** [comment]
Hi @jkxplg,
We've been busy working on supporting the WITH clause and free text search,
Multiple relationships of the same relationship type between two nodes being pushed back, I'll update here in case something changes.

**Comment by esokullu** [comment]
In a social network context, this is a very important feature. Think of React (or Comment) as an edge between User and Doc nodes. You'd need multiple React edges  so that users can like/comment on the same post multiple times. 

That's why I believe this is a crucial feature, that should be a higher priority on your list.

Thank you.

**Comment by swilly22** [comment]
@esokullu, I fully agree on the importance of this ability,
It took us a while to come up with a design with low performance impact, the plan is to start implementing  this week, I hope to push a PR in a couple of days.

**Comment by esokullu** [comment]
Thanks you @swilly22 much appreciated! Time to build & use :)
Cheers,
