### ISSUE TITLE
Can I compile on Linux SLES11?

### ISSUE THREAD

**Issue by rkedward** [RedisLabsModules/RedisGraph#323]
I can compile redis-sever with no issue.  But when I run make in the `RedisGraph` dir as instructed in the readme it fails with the following error:

```
(master|✔) % make
make -C ./src all
make[1]: Entering directory `/<base>/RedisGraph/src'
    CC /<base>/src/config.o
cc1: error: unrecognized command line option "-Wno-unused-result"
make[1]: *** /<basedir>/RedisGraph/src/config.o] Error 1
make[1]: Leaving directory `/<basedir>/RedisGraph/src'
make: *** [all] Error 2
```

Can someone offer a suggestion on what I can try?

**Comment by jeffreylovitz** [comment]
Hey @rkedward ,
What compiler are you using? I'd recommend installing `gcc` version 5 or greater.
