### ISSUE TITLE
Primitives for updates/batch updates

### ISSUE THREAD

**Issue by ldhulipala** [RedisLabsModules/RedisGraph#329]
Hi, I looked through the docs and demos and did not see any mention of how to _update_ graphs. Are vertex/edge updates possible with the current system? If so, please consider adding a section on how updates are handled in the design doc (https://oss.redislabs.com/redisgraph/design/#constructing-a-graph).

Specifically, I am curious how edge additions and deletions to a high-degree vertex are handled.

Thank you,
Laxman

**Comment by swilly22** [comment]
Demo on how to update a vertex/edge attribute:
https://github.com/RedisLabsModules/RedisGraph/blob/master/demo/social/social_queries.py#L157

Reference to our documentation on how to perform updates:
https://oss.redislabs.com/redisgraph/commands/#set

Edge additions and deletions:
https://oss.redislabs.com/redisgraph/commands/#create
https://oss.redislabs.com/redisgraph/commands/#delete
https://github.com/RedisLabsModules/RedisGraph/blob/master/demo/social/social_queries.py#L339

**Comment by ldhulipala** [comment]
Thanks for your help!
