### ISSUE TITLE
Support Lua scripting and MULTI/EXEC

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RedisGraph#333]
I'd like to be able to do `GRAPH.QUERY` commands in a Lua script but I get `Blocking module command called from Lua script` issues. Additionally, I'd like to be able to run MULTI/EXEC blocks but they don't seem to be supported either.

**Comment by swilly22** [comment]
#352

**Comment by mayureshkumbhar** [comment]
@swilly22 
Tried to execute cypher commands as single transaction using `WATCH/MULTI/EXEC`, but could its executing as pipeline not transaction. Please find below code for reference.

Third graph CREATE command is failing as one of its param is commented, as expected its failing with `redis.clients.jedis.exceptions.JedisDataException: Missing parameters` still its not reverting earlier changes done by first two GRAPH CREATE. 


> try(RedisGraph graph = new RedisGraph();
        	RedisGraphContext context = graph.getContext()) {
        	Map<String, Object> params = new HashMap<>();
            params.put("age", 30);
            //Deliberately commented this line to fail the transaction   
            //params.put("name", "amit");
			// WATCH/MULTI/EXEC
            context.watch("contextSocial");
            RedisGraphTransaction t = context.multi();
            Response<ResultSet> r1 = t.query("contextSocial","CREATE (:person{name:'roi',age:32})");
            Response<ResultSet> rmk = t.query("contextSocial","CREATE (:person{name:'mk',age:30})");
            Response<ResultSet> r2 = t.query("contextSocial","CREATE (:person{name:$name,age:$age})", params);
            Response<ResultSet> r3 = t.query("contextSocial", "MATCH (a:person), (b:person) WHERE (a.name = 'roi' AND b.name='mk') CREATE (a)-[:knows]->(b)");
            Response<ResultSet> r4 = t.query("contextSocial", "MATCH (a:person), (b:person) WHERE (a.name = 'amit' AND b.name='mk') CREATE (a)-[:fof]->(b)");
            List<Object> execResults =  t.exec();
            System.out.println(execResults.toString());
            //context.deleteGraph("contextSocial");
        }
Output

> [ResultSetImpl{header=HeaderImpl{schemaTypes=[], schemaNames=[]}, statistics=StatisticsImpl{statistics={Labels added=1, Nodes created=1, Properties set=2, Query internal execution time=0.263100 milliseconds}}, results=[]}, ResultSetImpl{header=HeaderImpl{schemaTypes=[], schemaNames=[]}, statistics=StatisticsImpl{statistics={Nodes created=1, Properties set=2, Query internal execution time=0.107500 milliseconds}}, results=[]}, redis.clients.jedis.exceptions.JedisDataException: Missing parameters, ResultSetImpl{header=HeaderImpl{schemaTypes=[], schemaNames=[]}, statistics=StatisticsImpl{statistics={Relationships created=1, Query internal execution time=0.414600 milliseconds}}, results=[]}, ResultSetImpl{header=HeaderImpl{schemaTypes=[], schemaNames=[]}, statistics=StatisticsImpl{statistics={Query internal execution time=0.277200 milliseconds}}, results=[]}]

**Comment by DvirDukhan** [comment]
@mayureshkumbhar 
As far as I know, the Redis pipeline does not support rollbacks for failing executions within the pipeline, so the success of your first two queries will be shown in your graph. More generally speaking, RedisGraph currently does not support transactions or rollbacks for failing queries.

**Comment by mayureshkumbhar** [comment]
@DvirDukhan , Is there any way we could implement atomic execution of graph queries or transactional behaviour in Redisgraph

**Comment by DvirDukhan** [comment]
@mayureshkumbhar 
Regarding atomic execution, I think you can use Lua scripts as they are executed on the main thread. But this will not guarantee you the rollback option.
Regarding transactional behavior, I'm sorry, but I think that every solution that I might suggest will probably be wrong since we do not support it. We just started designing transactional behavior on RedisGraph. I cannot commit on the features or ETA since it is in very early stages.

**Comment by mayureshkumbhar** [comment]
Thank you @DvirDukhan
