### ISSUE TITLE
Adding ORDER BY changes the number of returned hits when used in combination with LIMIT

### ISSUE THREAD

**Issue by dipeti** [RedisLabsModules/RedisGraph#359]
Please consider a graph below:
```
CREATE (:PARENT {name: 'Stevie'})
CREATE (:PARENT {name: 'Mike'})
CREATE (:PARENT {name: 'James'})
CREATE (:PARENT {name: 'Rich'})

#Stevie has got 3 children
MATCH (p:PARENT {name: 'Stevie'}) CREATE (p)-[:HAS]->(c:CHILD {name: 'child1'})
MATCH (p:PARENT {name: 'Stevie'}) CREATE (p)-[:HAS]->(c:CHILD {name: 'child2'})
MATCH (p:PARENT {name: 'Stevie'}) CREATE (p)-[:HAS]->(c:CHILD {name: 'child3'})

#Mike has got 1 child
MATCH (p:PARENT {name: 'Mike'}) CREATE (p)-[:HAS]->(c:CHILD {name: 'child4'})

#James has got 2 children
MATCH (p:PARENT {name: 'James'}) CREATE (p)-[:HAS]->(c:CHILD {name: 'child5'})
MATCH (p:PARENT {name: 'James'}) CREATE (p)-[:HAS]->(c:CHILD {name: 'child6'})
```
I have got a graph of 4 `PARENT` nodes 3 of which have got at least one `CHILD` nodes. I would like to run a query that returns all those `PARENT` nodes that have at least one `CHILD`, ordered by name, and with hits limited to 2. I expect to see Mike and James in the result set.
`MATCH (p:PARENT)-[:HAS]->(:CHILD) RETURN DISTINCT p ORDER BY p.name LIMIT 2`
However, only James pops up. Incidentally, when running the query without the `ORDER BY` clause I get back 2 hits which leads me to believe that `ORDER BY` - erroneously -  affects the number of hits. 

Can you look into this please? Thanks

**Comment by swilly22** [comment]
Hi @dipeti,
Indeed this is a bug, we'll try to get this one solved ASAP.
Thank you!

**Comment by swilly22** [comment]
#384
