### ISSUE TITLE
Properties showing from other labels / nodes

### ISSUE THREAD

**Issue by srikanthdasari** [RedisLabsModules/RedisGraph#366]
hi,

i have a basic question, not sure is it already asked here..

i have created a two nodes with few different properties, but the all the union properties are showing up in both the nodes.

![image](https://user-images.githubusercontent.com/7415989/52908669-6a105480-3248-11e9-8a33-3d83e95bb85d.png)

![image](https://user-images.githubusercontent.com/7415989/52908653-fec68280-3247-11e9-94da-33d2c5926c3c.png)

**Comment by swilly22** [comment]
Hi,
The way RedisGraph works at the moment (subject to change once we'll support returning full entities),
is by expanding "collapsed" entities such as in the query you've provided `(n)`.
by looking at the `MATCH` clause we encounter a node `N` which isn't labeled, as such RedisGraph gathers all schema information (attributes) it ever encountered for nodes.

If you want to filter on a node label please specify it within the node as such: `(n:group)`

**Comment by srikanthdasari** [comment]
got it...

thank you very much
