### ISSUE TITLE
Floating point numbers unexpectedly rounded

### ISSUE THREAD

**Issue by jonathanschulberger** [RedisLabsModules/RedisGraph#377]
**OS**:               Debian 9
**Redis**:           5.0.3
**RedisGraph**: 1.0.13, 1.0.14

_Setup (either 1.0.13 or 1.0.14)_
```
GRAPH.QUERY fp "CREATE (d:data{value:12345.6789})"
1) (empty list or set)
2) 1) "Nodes created: 1"
   2) "Properties set: 1"
   3) "Query internal execution time: 0.535672 milliseconds"
```

_Retrieval (1.0.13)_
```
GRAPH.QUERY fp "MATCH (n) RETURN n"
1) 1) 1) "n.value"
   2) 1) "12345.678900"
2) 1) "Query internal execution time: 0.280904 milliseconds"
```

_Retrieval (1.0.14)_
```
GRAPH.QUERY fp "MATCH (n) RETURN n"
1) 1) 1) "n.value"
   2) 1) "12345.7"
2) 1) "Query internal execution time: 0.254889 milliseconds"
```

As you can see, querying floating point values with 1.0.14 results in a number rounded to 6 significant digits. As far as I can tell, this is a bug unless I missed a configuration issue somewhere. I'll be more than happy to provide any other information or perform any other debugging if requested.

**Comment by jeffreylovitz** [comment]
@jonathanschulberger Thanks for the report! Internally, floating-point values are stored as standard 64-bit doubles, so your data is not getting truncated.

The recent modifications to our print formatters cause this rounding in replies, though, which is definitely inadequate. We'll try to improve this quickly, and I'll update here!
