### ISSUE TITLE
pagerank algorithm?

### ISSUE THREAD

**Issue by wuyanxing** [RedisLabsModules/RedisGraph#398]

**Comment by swilly22** [comment]
Due to other priorities pagerank has been delayed, I'll share that the implementation is done, all that's left is figuring out a proper way of calling graph algorithms.

I will update here once this is done.

**Comment by wuyanxing** [comment]
thanks

**Comment by wuyanxing** [comment]
Other algorithm will be updated too?

like shortest paths, K-core,K-neighborhood...

**Comment by K-Jo** [comment]
hi @wuyanxing  Once we finalise how we would call such algorithms and the Pagerank reference implementation is in place, we believe that the community can help scale out more algorithms quite easily.  as @swilly22 we'll update you here on our progress

**Comment by swilly22** [comment]
Duplicate #304

**Comment by K-Jo** [comment]
@wuyanxing can we close this issue since it's a duplicate as indicated above?

**Comment by wuyanxing** [comment]
Yeach. I thought so,
