### ISSUE TITLE
basic relationship pattern doesn't work

### ISSUE THREAD

**Issue by snowytoxa** [RedisLabsModules/RedisGraph#414]
Hi,

following simple query doesn't work:
```
127.0.0.1:6379> GRAPH.QUERY imdb 'MATCH (a)-[]-(b) RETURN b'
(error) Syntax error at offset 14 near '-'
```
v1.0.15

it is also expected to work due to the example in the official documentation:
https://oss.redislabs.com/redisgraph/commands/#variable-length-relationships

**Comment by jeffreylovitz** [comment]
hi @snowytoxa,

We don't yet support undirected relationships; the forms we would currently accept are `MATCH (a)-[]->(b) RETURN b` or `MATCH (a)<-[]-(b) RETURN b`.

This is documented under https://oss.redislabs.com/redisgraph/cypher_support/#structural-types

**Comment by snowytoxa** [comment]
Ok, I was expecting it. in that case, the example the link I gave to should be fixed.
https://oss.redislabs.com/redisgraph/commands/#variable-length-relationships

**Comment by jeffreylovitz** [comment]
Agreed! I'll make that change shortly.
