### ISSUE TITLE
LIMIT by specific alias

### ISSUE THREAD

**Issue by elvis197686** [RedisLabsModules/RedisGraph#418]
At the moment we can only SKIP/LIMIT by individual results items, however we want to sometimes limit by a specific alias, that may not be distinct between result items.

For example, say we have a graph command with 2 levels of alias returned:

`MATCH (e:EVENT {id: 'EVENT_1'})-[:HAS]->(m:MARKET)-[:HAS]->(s:SELECTION) RETURN e,m,s LIMIT 10`

This will return a maximum of 10 selections, however we want to paginate by market (i.e. limit the number of markets to 10, not selections), so we want to do something like:

`MATCH (e:EVENT {id: 'EVENT_1'})-[:HAS]->(m:MARKET)-[:HAS]->(s:SELECTION) RETURN e,m,s LIMIT m BY 10`

Is there anything in the product roadmap to provide this feature?

**Comment by K-Jo** [comment]
HI @elvis197686, this is definitely on our roadmap `with` highest priority.  Once we finalise #318 we will make sure this limitation is solved: https://oss.redislabs.com/redisgraph/known_limitations/#using-nodes-and-relationships-specified-in-with-clause-in-multiple-patterns and you should be able to run a query like this:
```
MATCH (e:EVENT {id: 'EVENT_1'})-[:HAS]->(m:MARKET)
WITH e, m LIMIT 10
MATCH (m:MARKET)-[:HAS]->(s:SELECTION)
RETURN e,m,s
```

**Comment by elvis197686** [comment]
That's great thanks!

**Comment by elvis197686** [comment]
Good Day Redis.. just wandering what the status of this issue is now? It is becoming quite a concern for us as we are having to write a significant number of work-arounds in the meantime.

**Comment by swilly22** [comment]
Hi @elvis197686,
We're still working on migrating to the new Cypher parser, estimating 1 month worth of work.
apologies for the delay.

**Comment by elvis197686** [comment]
Ok, thanks.

Sorry but I have a follow-up question: Is that cypher work part of RedisGraph 2.0? I noticed that is a project and was wandering what was in it to make it a major release.

**Comment by swilly22** [comment]
indeed it is.

**Comment by K-Jo** [comment]
closing this issue and tracking this further in #466
