### ISSUE TITLE
Slower than expected relationship insertion

### ISSUE THREAD

**Issue by colinfike** [RedisLabsModules/RedisGraph#421]
I'm currently working on a small project with a data set of around 600,000 nodes and 600,000 relationships. I saw the benchmarks for insertion here https://oss.redislabs.com/redisgraph/design/ and was surprised to see that finding two nodes (with indices) and creating a relationship between them was taking around 4 ms from my testing. 4ms per relationship is quite far away from 500,000 relationships in 300ms from that design page.

I am running this on a r4.8xlarge which is the same machine the benchmark article published by RedisLabs utilized. I'm going to continue tinkering with configuration and see if anything shakes out but I was wondering if there were any quick wins for me to try. I know there is the bulk insert python utility but that doesn't quite fit my use case. Perhaps the benchmarks were generated based on using that tool for insertions.

A little extra information, I am connecting two different types of nodes with a relationship in the above example. 

EDIT: I have been trying the following query and changing the filters a bit and I have seen the "Query internal execution time" jump from 0.2 ms to ~4 ms with no discernible reason on my end. Note that in this example I am relating two nodes of the same type.

`graph.query test_db "match (a:node_a {ident: 'love'}),(b:node_a {ident: 'jam'}) create (a)-[:test]->(b)"`

Thanks.

**Comment by swilly22** [comment]
Hi @colinfike,
Indeed the benchmarked graph creation was done using the bulk-insert script, which is optimised specifically for that task,

Would you mind sharing the execution-plan for queries you're experiencing slowness with?
Simply replace `GRAPH.QUERY` with `GRAPH.EXPLAIN`

Thank you.

**Comment by colinfike** [comment]
Hey @swilly22,

Sure that's no problem. For context, I only created the nodes without making any relationships before running this.

```
127.0.0.1:6379> graph.explain test_db "match (a:page {display: 'born'}),(b:page {display: 'zebra'}) create (a)-[:test]->(b)"
"Create\n    Cartesian Product\n        Index Scan\n        Index Scan\n"

127.0.0.1:6379> graph.query test_db "match (a:page {display: 'born'}),(b:page {display: 'zebra'}) create (a)-[:test]->(b)"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 3.643000 milliseconds"
```

I ran a few more queries of the same type but swapped out the value of the `display` filter. Most of them were around the same execution time but I managed to get one that finished much faster.
```
127.0.0.1:6379> graph.query test_db "match (a:page {display: 'there'}),(b:page {display: 'zebra'}) create (a)-[:test]->(b)"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 0.163000 milliseconds"
127.0.0.1:6379> graph.explain test_db "match (a:page {display: 'there'}),(b:page {display: 'zebra'}) create (a)-[:test]->(b)"
"Create\n    Cartesian Product\n        Index Scan\n        Index Scan\n"
```

Thanks!

There are ~230k page nodes and ~470k other nodes as well in the graph.

**Comment by swilly22** [comment]
I'll have to agree ~4ms for the above query sounds a bit slow, but looking at the execution plan it seems like RedisGraph is utilising its indices.

Which version of RedisGraph are you using?
Were there additional queries running concurrently while you were trying to perform `CREATE`
Would it be possible to get the dataset to try and replicate what you're experiencing?

**Comment by colinfike** [comment]
Here is the output of `MODULE LIST`, I believe this is the latest version. I pulled the repo and compiled just a few days ago.
```
1) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 10015
```

There were no other queries running at the time of me running those commands in the CLI.

I am able to send you an obfuscated dataset that I am using. The data model is very basic, just two different types of nodes with a single field on each. Create a `pages` node for each line in the pages seed data setting the `display` property equal to the integer on that line. Create a `other_node` node for each line in the Other Node seed data setting the `id` property equal to the UUID on each line.

Pages Seed Data: https://gist.github.com/colinfike/ad5fb069b7741d78aa039e85a7494d77

Other Page Seed Data: https://gist.github.com/colinfike/684865fa5d1a59f8124c0c4b31d5413c

I imported those nodes and ran the following on the r4.8xlarge. The only thing I'm running on that ec2 instance is the redis-server and the redis-cli.

```
127.0.0.1:6379> graph.query test_db "match (a:pages) return count(a)"
1) 1) 1) "count(a)"
   2) 1) (integer) 234719
2) 1) "Query internal execution time: 23.306185 milliseconds"
127.0.0.1:6379> graph.query test_db "match (a:other_node) return count(a)"
1) 1) 1) "count(a)"
   2) 1) (integer) 472376
2) 1) "Query internal execution time: 48.917211 milliseconds"
127.0.0.1:6379> graph.explain test_db "match (a:pages {display: '0'}), (b:other_node {id: 'u3bb48a285cbafaf0.-3bc55cee.14d9e7b2d98.2a8e'}) create (a)-[:entry]->(b)"
"Create\n    Cartesian Product\n        Index Scan\n        Index Scan\n"
127.0.0.1:6379> graph.query test_db "match (a:pages {display: '0'}), (b:other_node {id: 'u3bb48a285cbafaf0.-3bc55cee.14d9e7b2d98.2a8e'}) create (a)-[:entry]->(b)"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 3.794278 milliseconds"
```

**Comment by colinfike** [comment]
@swilly22 Hey just checking if you had an opportunity to test out the data set I provided. I played around a little more with the Redis configuration and didn't really see much of an impact. If the performance I have seen so far is expected that is totally fine, I'm just trying to understand if there is something else going on.

**Comment by swilly22** [comment]
Hi @colinfike,
I'm getting the same results, although when trying to simply retrieve the two nodes execution time is way below millisecond.

```
127.0.0.1:6379> graph.query colinfike "match (a:pages {display: 2}), (b:other_node {id: 'u3bb48a285cbafaf0.-3bc55cee.14d9e7b2d98.2a8e'}) create (a)-[:entry]->(b)"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 4.849000 milliseconds"
```

```
127.0.0.1:6379> graph.query colinfike "match (a:pages {display: 2}), (b:other_node {id: 'u3bb48a285cbafaf0.-3bc55cee.14d9e7b2d98.2a8e'}) return a,b"
1) 1) 1) "a.display"
      2) "b.id"
   2) 1) "2"
      2) "u3bb48a285cbafaf0.-3bc55cee.14d9e7b2d98.2a8e"
2) 1) "Query internal execution time: 0.146000 milliseconds"
```

I'll have to do some profiling.

**Comment by swilly22** [comment]
I've tried benchmarking the query using redis-benchmark:

`redis-benchmark -c 1 GRAPH.QUERY colinfike "match (a:pages {display: 0}), (b:other_node {id: 'u3bb48a285cbafaf0.-3bc55cee.14d9e7b2d98.2a8e'}) create (a)-[:entry]->(b)"`

output:

```
====== GRAPH.QUERY colinfike match (a:pages {display: 0}), (b:other_node {id: 'u3bb48a285cbafaf0.-3bc55cee.14d9e7b2d98.2a8e'}) create (a)-[:entry]->(b) ======
  100000 requests completed in 21.56 seconds
  1 parallel clients
  3 bytes payload
  keep alive: 1

99.97% <= 1 milliseconds
100.00% <= 2 milliseconds
100.00% <= 2 milliseconds
4639.08 requests per second
```

I've restarted RedisGraph, reloaded the data and ran the query multiple times from RedisCLI:

First run
```
GRAPH.QUERY colinfike "match (a:pages {display: 0}), (b:other_node {id: 'u3bb48a285cbafaf0.-3bc55cee.14d9e7b2d98.2a8e'}) create (a)-[:entry]->(b)"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 2.781000 milliseconds"

Second run ... N run execution times:
3.806000 ms
0.165000 ms
0.197000 ms
0.179000 ms
0.187000 ms
0.175000 ms
0.136000 ms
0.227000 ms
0.160000 ms
0.134000 ms
0.135000 ms
0.167000 ms
0.141000 ms
0.182000 ms
0.130000 ms
0.172000 ms
0.131000 ms
0.219000 ms
0.145000 ms
0.155000 ms
0.132000 ms
0.136000 ms
0.163000 ms
0.141000 ms

The first couple of inserts take dramatically longer time, this is probably due to matrix creation whenever a new edge type is introduced.

**Comment by colinfike** [comment]
@swilly22 Thanks for checking out the data set and thank you very much for all your help so far.

I replicated your tests and got the same results when benchmarking that single query. I tried making something a little more robust that replicates the actual logic I'd be using with RedisGraph.

[cutQueries.txt](https://github.com/RedisLabsModules/RedisGraph/files/3051019/cutQueries.txt)

I made the text file above with 50k queries that create relationships between `pages` and `other_nodes` that I stdin'd to `redis-cli`. While some of these queries have the same `pages`/`other_nodes` in them, these are more or less unique pairings. My results when running this have the queries finishing around 3-4 ms pretty consistently throughout the runtime of the script. 

```
redis-cli < cutQueries.txt
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 0.230000 milliseconds"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 5.572000 milliseconds"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 4.941000 milliseconds"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 3.554000 milliseconds"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 3.547000 milliseconds"
1) (empty list or set)
2) 1) "Relationships created: 1"
   2) "Query internal execution time: 3.551000 milliseconds"
...
```

**Comment by swilly22** [comment]
Thanks!
I was able to reproduce your results, the issue here is whenever we introduce a change to a GraphBLAS matrix (connecting two nodes) the following query will have to apply that change by synchronising the matrix, this operation which takes time.

Let me see if there's something I can do about this.

**Comment by swilly22** [comment]
@colinfike Please retry using branch `avoid-matrix-sync`
Let me know if consecutive create queries are within the 0.2 ms latency range.

**Comment by colinfike** [comment]
@swilly22 Yup I'm now seeing the queries complete in the 0.2 ms range. Thanks for taking a look at this, excited to continue using RedisGraph.
