### ISSUE TITLE
AWS Support

### ISSUE THREAD

**Issue by elenigen** [RedisLabsModules/RedisGraph#432]
[Question] I would guess there's no simple way for now to integrate this module to an AWS Redis instance (if it's the case I would like to know more and I'm not talking about a EC2 instance), but have you considered contacting AWS to see if they would be willing to do so?  I know it's a competitor to AWS Neptune DB, but it would still be nice to have the choice.

**Comment by K-Jo** [comment]
@elenigen I'm assuming you're looking for a managed solution, but please advice if you also meant unmanaged:
If you would like to have a fully managed service of RedisGraph, the only option is by using [Redis Cloud Pro](https://redislabs.com/redis-enterprise/pro/). For more information on why, I refer you to this [blogpost](https://redislabs.com/blog/redis-labs-modules-license-changes/)

**Comment by elenigen** [comment]
Yes, I'm looking for a managed solution.  Thanks for sharing this post, but I'm confused, it sounds like cloud service providers are no longer allowed to use the Redis open source project to build their own solution, while I still see AWS upgrading Redis to 5.0.2 ... so it looks like they still continue to do so, which means I misunderstood the post.

**Comment by K-Jo** [comment]
@elenigen The blogpost explains clearly what falls under which license.  Redis was, is, and will remain BSD 3-Clause. The modules listed in the [blogpost](https://redislabs.com/blog/redis-labs-modules-license-changes/), fall under a different license, so does RedisGraph.   Please advise if it's clear and if we can close this issue.

**Comment by elenigen** [comment]
Thanks for the explanation, yes please close this issue.
