### ISSUE TITLE
Redis crash when referencing not existent value

### ISSUE THREAD

**Issue by madmac2501** [RedisLabsModules/RedisGraph#435]
Sorry if this has been already reported. Running these queries crash redis, I've tested with redisgraph docker edge. I would expect that an unknown value starts with the value 0 for numbers and the empy strings for string.

GRAPH.QUERY test "MERGE (s {key: 'value'}) SET s.num = s.num + 32"

GRAPH.QUERY test "MERGE (s1 {key: 'value1'})-[r:SENTS]->(s2 {key: 'value2'}) SET r.num = r.num + 5"

**Comment by swilly22** [comment]
Hi @madmac2501,
Thank you for reporting,

checking with Neo4J,
The query `GRAPH.QUERY test "MERGE (s {key: 'value'}) SET s.num = s.num + 32"`
will create the node `s` if it doesn't exists, in which case `num` will not be set, neo's output: `Created 1 node, set 1 property`

I'll try to introduce a fix which complies with Neo's behavior

**Comment by madmac2501** [comment]
What query would I need to do to create node "s" and set or update the attribute s.num? My idea is to not have an especial query for creation vs updating of a node.

Thanks!

**Comment by swilly22** [comment]
If we were to support [ON CREATE and ON MATCH](https://neo4j.com/docs/cypher-manual/current/clauses/merge/#query-merge-on-create-on-match) then that would be the way to go,

Unfortunately I don't see a way around this but to perform this creation/update into multiple queries,
Support for the `ON CREATE` and `ON MATCH` should be available once we'll replace our current parser.

**Comment by swilly22** [comment]
Crash fixed #438

**Comment by madmac2501** [comment]
@swilly22 I just build redisgraph from source and tested this. I see that two properties are set and that "num" is set to null. I don't a neo4j to test, but you said that properties set should be 1. Do I create a new issue in github?

127.0.0.1:6379> GRAPH.QUERY test "MERGE (s {key: 'value'}) SET s.num = s.num + 32"
1) (empty list or set)
2) 1) "Nodes created: 1"
   2) "Properties set: 2"
   3) "Query internal execution time: 0.374027 milliseconds"

**Comment by swilly22** [comment]
Indeed, the statistics report here is wrong, thank you for pointing this out.
