### ISSUE TITLE
Add support for MEDIAN aggregation

### ISSUE THREAD

**Issue by gkorland** [RedisLabsModules/RedisGraph#447]

**Comment by jeffreylovitz** [comment]
We have `stDev` and stDevP`functions, as well as two for calculating percentiles. I agree that median would be nice, though.

**Comment by gkorland** [comment]
Sorry my mistake... wrong project...

**Comment by jeffreylovitz** [comment]
As `PercentileDisc([property], 0.5)` returns the median, and Cypher does not presently have a median function, I'm going to close this if no one objects!
