### ISSUE TITLE
Overlapping MATCH clauses and the "Properties set" count

### ISSUE THREAD

**Issue by epswartz** [RedisLabsModules/RedisGraph#457]
Hey, I discovered some interesting numbers when some code I wrote accidentally put the same value for a bunch of `MATCH` clauses. Not sure if this is a problem, but I'd like to understand what's going on.

wondering if anyone can help explain for me what it is that's happening here:

If I create 2 nodes, identical to each other:

```
GRAPH.QUERY test "CREATE (n0:Person {name:'Ethan'}), (n1:Person {name:'Ethan'})"
```

and then do a `MATCH/SET` that matches them both and sets a property:

```
GRAPH.QUERY test "MATCH (n0:Person {name:'Ethan'}), (n1:Person {name:'Ethan'}) SET n0.age=23"
```

I see `Properties set: 4`. This makes sense to me - the first `MATCH` would match both nodes, the second `MATCH` would match both nodes, and altogether, that's 4. But, if I then create 2 more nodes and then run the match again (this also works if you make all 4 nodes at once):

```
GRAPH.QUERY test "CREATE (n0:Person {name:'Ethan'}), (n1:Person {name:'Ethan'})"
GRAPH.QUERY test "MATCH (n0:Person {name:'Ethan'}), (n1:Person {name:'Ethan'}) SET n0.age=23"
```

I would expect to see `Properties set: 8`, since each `MATCH` would match all 4 nodes, and there are 2 `MATCH` clauses. Instead, I see `Properties set: 16`.

After some investigation, this pattern continues: The `Properties set` count is the number of matched nodes to the power of the number of matches, times the number of SETs. For example with 3 nodes, 4 matches and 2 sets:

```
GRAPH.QUERY test "CREATE (n0:Person {name:'Ethan'}), (n1:Person {name:'Ethan'}),  (n2:Person {name:'Ethan'})"
GRAPH.QUERY test "MATCH (n0:Person {name:'Ethan'}), (n1:Person {name:'Ethan'}), (n2:Person {name:'Ethan'}), (n3:Person {name:'Ethan'}) SET n0.age=23, n1.age=23"
```

We get `Properties set: 162`, or (3^4)*2.

Is this just a bizarre misuse of openCypher? Should I just make sure my `MATCH` clauses don't overlap too much? Anything else I should try or investigate? Any insight into why the number grows exponentially with the number of `MATCH`es is appreciated.

Thanks for any help, have a good one :)

**Comment by jeffreylovitz** [comment]
Hey @epswartz,

In openCypher, comma-separated patterns in MATCH clauses are considered to be disconnected, and form Cartesian products (the equivalent of a FULL JOIN in SQL). In a Cartesian product, every valid conjunction of items is returned. Taking as an example your 2-node graph:
```
GRAPH.QUERY test "CREATE (n0:Person {name:'Ethan'}), (n1:Person {name:'Ethan'})"
GRAPH.QUERY test "MATCH (n0:Person {name:'Ethan'}), (n1:Person {name:'Ethan'}) RETURN ID(n0), ID(n1)"
1) 1) 1) "ID(n0)"
      2) "ID(n1)"
   2) 1) (integer) 0
      2) (integer) 0
   3) 1) (integer) 1
      2) (integer) 0
   4) 1) (integer) 0
      2) (integer) 1
   5) 1) (integer) 1
      2) (integer) 1
```
Specifying 2 comma-separated patterns that each match both entities gives us 4 results - a truth table, in this case, which is kind of cool but probably not what you want!

Since your SET clause specifies two properties, we (# of nodes) ^ (# of match patterns) * 2.

**Comment by epswartz** [comment]
Thanks! This is really helpful, I think I understand what's going on here.
