### ISSUE TITLE
Support for multiple join paths in a single query

### ISSUE THREAD

**Issue by elvis197686** [RedisLabsModules/RedisGraph#468]
This may or may not already be supported - please let us know whether we can do it in a single query, and if not whether support for such a query is in the roadmap.

BTW this is a continuation from our question about branching queries (#465).

We have a model which allows for 2 relation paths between 2 nodes, one via an intermediate node:

GENRE [HAS] SUBGENRE [HAS] BOOKS
GENRE [CONTAINS] BOOKS

For the purposes of this example, we assume some genres do not have sub-genres and we do not want to make a node (a dummy sub-genre) unless we have to.

So, we want a single query to return the books for a given genre, regardless of whether the genre has sub-genres - how can we do that?

I suspect it requires support for "OR", which is covered by issue #464 , but I just want to be sure before we commit to the work-round of creating dummy nodes.

**Comment by swilly22** [comment]
Hi @elvis197686,

`MATCH (g:GENRE)-[*1..2]->(b:BOOK) RETURN g,b` will find all books 1,2 hops away from a genre regardless of the edge type.

BTW #464 refers to index utilisation where the indexed filter property is mentioned multiple times using an OR, e.g. `WHERE age > 30 OR age < 60`
In which case the index isn't utilised.

**Comment by elvis197686** [comment]
Thanks for the quick response and the great tip - that sounds very powerful. Now you mention the number of hops, it all makes sense!
