### ISSUE TITLE
Query using MATCH .. MATCH .. WHERE ID(..) = ID(..) gives inconsistent results

### ISSUE THREAD

**Issue by elvis197686** [RedisLabsModules/RedisGraph#469]
[This is related to issue #465, where the idea to use the `MATCH .. MATCH .. WHERE ID(..) = ID(..) ` pattern was suggested.]

We are getting inconsistent results when using the above query pattern. I have attached a set of commands 
[REDIS_BOOK_GENRE_TEST.txt](https://github.com/RedisLabsModules/RedisGraph/files/3112709/REDIS_BOOK_GENRE_TEST.txt)
 to populate a graph db with the following structure:

BOOKSTORE [HAS] BOOKS [HAS] PAGES
GENRE [HAS] SUBGENRE [HAS] BOOKS

The bookstore has a couple of books, each book has a genrename property. This property relates to either a genre or a subgenre.

Anyway, when executing the following command we initially get 1 result (actually it appears to be wrong as it only returns 1 page of a book that has 2 pages associated), but more importantly on second execution it returns no results. Further executions of that query return no results.

```graph.query BG_EX "MATCH (mg:GENRE)-[*1..2]->(m:BOOK) MATCH (e:BOOKSTORE)-[:HAS]->(ma:BOOK)-[:HAS]->(s:PAGE) WHERE mg.genrename = 'example' AND ID(m) = ID(ma) return mg, e, ma, s"```

This inconsistent behaviour has been observed using both the `latest` and `edge` docker images.

**Comment by jeffreylovitz** [comment]
@elvis197686 Thanks for providing the build commands! That was very helpful.

This was a minor bug in the logic combining variable length traversals with multiple MATCH clauses. I've just written a fix that should be merged shortly.

Following the fix, your query returns:
```
1) 1)  1) "mg.id"
       2) "mg.name"
       3) "mg.displayOrder"
       4) "mg.genrename"
       5) "e.id"
       6) "e.name"
       7) "e.bsprop"
       8) "ma.id"
       9) "ma.name"
      10) "ma.prop"
      11) "ma.genrename"
      12) "s.id"
      13) "s.name"
      14) "s.prop"
   2)  1) "GENRE1"
       2) "GENRE1"
       3) (integer) 3
       4) "example"
       5) "BS1"
       6) "BS1"
       7) (integer) 12
       8) "BOOK11"
       9) "BOOK1"
      10) (integer) 2
      11) "example"
      12) "PAGE111"
      13) "PAGE111"
      14) (integer) 2
   3)  1) "GENRE1"
       2) "GENRE1"
       3) (integer) 3
       4) "example"
       5) "BS1"
       6) "BS1"
       7) (integer) 12
       8) "BOOK11"
       9) "BOOK1"
      10) (integer) 2
      11) "example"
      12) "PAGE112"
      13) "PAGE112"
      14) (integer) 2
```
Which seems to be accurate, though please correct me if you see any issues. This result is consistent upon repeated queries.

**Comment by swilly22** [comment]
@elvis197686, fix has been merged, thank you for reporting, sorry for the inconvenience.

**Comment by elvis197686** [comment]
I have tried the latest version and all appears to be good. You can close this issue.

Thanks!
